version: '3.8'

services:
  client:
    build: ./packages/client
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://client:3000
    depends_on:
      - ws
      - server

  ws:
    build: ./packages/ws
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://server:3000
    depends_on:
      - server

  server:
    build: ./packages/server
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
