service: chat-backend

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DB_URL: mongodb://localhost:27017
    DB_NAME: modern-chat
    DB_USERS_COLLECTION: users

functions:
  createUser:
    handler: src/handler.createUser
    events:
      - httpApi:
          path: /api/users
          method: POST
