service: chat-backend

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DB_URL: mongodb://localhost:27017
    DB_NAME: modern-chat
    DB_USERS_COLLECTION: users
    DB_MESSAGES_COLLECTION: messages
    JWT_SECRET: modern-chat

functions:
  register:
    handler: src/handler.register
    events:
      - httpApi:
          path: /api/register
          method: POST
  
  login:
    handler: src/handler.login
    events:
      - httpApi:
          path: /api/login
          method: POST
  
  getMessages:
    handler: src/handler.getMessages
    events:
      - httpApi:
          path: /api/messages
          method: GET
  
  sendMessage:
    handler: src/handler.sendMessage
    events:
      - httpApi:
          path: /api/send-message
          method: POST
